[package]
name = "socks"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "socks_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
uuid = { version = "1", features = ["v4", "serde"] }
ipnet = "2"
tokio = { version = "1", features = [
    "macros",
    "sync",
    "time",
    "process",
    "rt-multi-thread",
    "net",
] }
shadowsocks-service = { path = "../shadowsocks-rust/crates/shadowsocks-service", default-features = false, features = [
    "local",
    "local-tun",
    "aead-cipher",
    "aead-cipher-extra",
    "aead-cipher-2022",
    "aead-cipher-2022-extra",
    "hickory-dns",
    "local-dns",
    "local-http-rustls",
    "stream-cipher",
] }
