//! C ABI for the standard Shadowsocks data plane used by the macOS
//! NetworkExtension.
//!
//! The extension owns `NEPacketTunnelFlow`; this crate owns the userspace
//! TCP/IP + Shadowsocks stack. The two sides are bridged with:
//!
//! * [`socks_core_start`] / [`socks_core_stop`] — lifecycle,
//! * [`socks_core_push`] — inbound packets, batched,
//! * [`SocksSendFn`] — outbound packets,
//! * [`socks_core_notify_network_changed`] — path change notifications.
//!
//! The header (`core/include/socks_core.h`) is generated by cbindgen.

#![allow(clippy::missing_safety_doc)]

mod config;
mod device;
mod engine;

use std::{
    os::raw::{c_char, c_int, c_void},
    ptr,
};

pub use device::{SocksEventFn, SocksPacket, SocksSendFn};

/// Start the data plane. Returns `0` on success, non-zero on failure, in which
/// case `error_buffer` receives a NUL-terminated message.
///
/// `config_json` uses the standard Shadowsocks shape:
/// `{"server":..,"server_port":..,"method":..,"password":..}`.
/// `tunnel_address` / `tunnel_netmask` must match the address configured in
/// `NEPacketTunnelNetworkSettings`.
#[no_mangle]
pub unsafe extern "C" fn socks_core_start(
    config_json: *const c_char,
    tunnel_address: *const c_char,
    tunnel_netmask: *const c_char,
    send: SocksSendFn,
    event: SocksEventFn,
    ctx: *mut c_void,
    error_buffer: *mut c_char,
    error_buffer_len: usize,
) -> c_int {
    let result = (|| -> Result<(), String> {
        let config_json = read_cstr(config_json, "config_json")?;
        let tunnel_address = read_cstr(tunnel_address, "tunnel_address")?;
        let tunnel_netmask = read_cstr(tunnel_netmask, "tunnel_netmask")?;

        let config: config::StartConfig =
            serde_json::from_str(&config_json).map_err(|err| format!("invalid config JSON: {err}"))?;

        engine::start(
            config,
            &tunnel_address,
            &tunnel_netmask,
            send,
            event,
            ctx,
        )
    })();

    match result {
        Ok(()) => 0,
        Err(err) => {
            write_error(error_buffer, error_buffer_len, &err);
            -1
        }
    }
}

/// Enqueue packets read from the tunnel. Returns `0` on success.
#[no_mangle]
pub unsafe extern "C" fn socks_core_push(packets: *const SocksPacket, count: usize) -> c_int {
    match engine::push(packets, count) {
        Ok(()) => 0,
        Err(err) => {
            log::warn!("socks_core_push failed: {err}");
            -1
        }
    }
}

/// Stop the data plane and release its resources. Safe to call when stopped.
#[no_mangle]
pub extern "C" fn socks_core_stop() -> c_int {
    match engine::stop() {
        Ok(()) => 0,
        Err(err) => {
            log::warn!("socks_core_stop failed: {err}");
            -1
        }
    }
}

/// Notify the core that the host's default network path changed.
#[no_mangle]
pub extern "C" fn socks_core_notify_network_changed() -> c_int {
    match engine::notify_network_changed() {
        Ok(()) => 0,
        Err(err) => {
            log::warn!("socks_core_notify_network_changed failed: {err}");
            -1
        }
    }
}

fn write_error(buffer: *mut c_char, buffer_len: usize, message: &str) {
    if buffer.is_null() || buffer_len == 0 {
        return;
    }
    let bytes = message.as_bytes();
    let len = bytes.len().min(buffer_len - 1);
    unsafe {
        ptr::copy_nonoverlapping(bytes.as_ptr().cast::<c_char>(), buffer, len);
        *buffer.add(len) = 0;
    }
}

unsafe fn read_cstr(pointer: *const c_char, label: &str) -> Result<String, String> {
    if pointer.is_null() {
        return Err(format!("{label} must not be null"));
    }
    std::ffi::CStr::from_ptr(pointer)
        .to_str()
        .map(str::to_owned)
        .map_err(|_| format!("{label} is not valid UTF-8"))
}
