/* socks-core: standard Shadowsocks userspace data plane for NEPacketTunnelProvider.
 * Generated by cbindgen from core/src/lib.rs. Do not edit by hand. */

#ifndef SOCKS_CORE_H
#define SOCKS_CORE_H

#pragma once

/* Generated by cbindgen. Regenerate with `cargo build -p socks-core`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * One raw IP packet, as seen by the native side.
 */
typedef struct SocksPacket {
  /**
   * Pointer to the packet bytes. Valid only for the duration of the call.
   */
  const uint8_t *data;
  /**
   * Length of the packet in bytes.
   */
  uintptr_t len;
} SocksPacket;

/**
 * Hands packets produced by the core back to the tunnel.
 *
 * Called from a core worker thread; implementations must be thread-safe.
 */
typedef void (*SocksSendFn)(const struct SocksPacket *packets, uintptr_t count, void *ctx);

/**
 * Reports a JSON event (`{"type":"status"|"traffic"|"error", ...}`).
 */
typedef void (*SocksEventFn)(const char *event_json, void *ctx);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Start the data plane. Returns `0` on success, non-zero on failure, in which
 * case `error_buffer` receives a NUL-terminated message.
 *
 * `config_json` uses the standard Shadowsocks shape:
 * `{"server":..,"server_port":..,"method":..,"password":..}`.
 * `tunnel_address` / `tunnel_netmask` must match the address configured in
 * `NEPacketTunnelNetworkSettings`.
 */
int socks_core_start(const char *config_json, const char *tunnel_address, const char *tunnel_netmask, SocksSendFn send, SocksEventFn event, void *ctx, char *error_buffer, uintptr_t error_buffer_len);

/**
 * Enqueue packets read from the tunnel. Returns `0` on success.
 */
int socks_core_push(const struct SocksPacket *packets, uintptr_t count);

/**
 * Stop the data plane and release its resources. Safe to call when stopped.
 */
int socks_core_stop(void);

/**
 * Notify the core that the host's default network path changed.
 */
int socks_core_notify_network_changed(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SOCKS_CORE_H */
